services:
  app:
    build: .
    ports:
      - "5173:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    env_file:
      - .env.docker

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: routewise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
