services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
<<<<<<< Updated upstream
      - "5173:5000"
=======
      - "3000:5000"
>>>>>>> Stashed changes
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: routewise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
